# Generated by Django 5.0.7 on 2024-07-17 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersManage', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Name_Item',
            field=models.CharField(default='Default Item', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='Order_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='items',
            name='Section',
            field=models.CharField(max_length=20, verbose_name='Section(Clasify)'),
        ),
    ]
