# Generated by Django 5.1 on 2024-08-08 05:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Success', 'success'), ('Info', 'info'), ('Wrong', 'wrong')], default='Info', max_length=20)),
                ('object_id_actor', models.PositiveBigIntegerField()),
                ('verb', models.CharField(max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_actor', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
